#!/bin/sh

case "$1" in
  start)
    echo "Starting aesdsocket now"
    start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
    ;;
  stop)
    echo "Stopping $(APP_NAME)"
    start-stop-daemon -K -n $(APP_NAME)
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0